// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge"
import { threecxBlock } from "./index"
import { auth } from "./auth"

export const threecxBlockSchema = parseBlockSchema(threecxBlock)
export const threecxCredentialsSchema = parseBlockCredentials(
  threecxBlock.id,
  auth,
)
